version: '3'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.136
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
